const songs=[
 {title:"Song 1",file:"songs/song1.mp3",cover:"images/cover1.jpg"},
 {title:"Song 2",file:"songs/song2.mp3",cover:"images/cover2.jpg"}
];
const JAMENDO_CLIENT_ID="9344e04f";
let currentSong=0,shuffleOn=false,repeatOn=false,liked=new Set(),source="local",youtubeId=null,jamendoTrack=null,youtubePlayer=null,youtubeReady=false,youtubeTimer=null;

const $=id=>document.getElementById(id);
const audio=$("audio"),title=$("title"),cover=$("cover"),playBtn=$("play"),prevBtn=$("prev"),nextBtn=$("next"),progress=$("progress"),currentTime=$("currentTime"),duration=$("duration"),volume=$("volume"),artist=$("artist"),likeBtn=$("like"),toast=$("toast"),search=$("search"),youtubeDock=$("youtubeDock"),shuffleBtn=$("shuffle"),repeatBtn=$("repeat");
const songCards=$("songCards"),searchCards=$("searchCards"),libraryGrid=$("libraryGrid");

function formatTime(t){if(!Number.isFinite(t))return"0:00";const m=Math.floor(t/60),s=Math.floor(t%60).toString().padStart(2,"0");return`${m}:${s}`}
function toastMsg(msg){if(!toast)return;toast.textContent=msg;toast.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove("show"),2600)}
function updateLike(){if(!likeBtn)return;likeBtn.innerHTML=liked.has(currentSong)?'<i class="fa-solid fa-heart"></i>':'<i class="fa-regular fa-heart"></i>';likeBtn.classList.toggle("liked",liked.has(currentSong))}
function stopYoutube(){if(youtubePlayer&&youtubeReady){try{youtubePlayer.stopVideo()}catch(e){}}clearInterval(youtubeTimer);youtubeTimer=null}
function stopExternal(){stopYoutube();jamendoTrack=null}
function setLocalSong(i,autoplay=false){if(!audio)return;stopExternal();source="local";youtubeId=null;if(youtubeDock)youtubeDock.classList.add("hidden");currentSong=(i+songs.length)%songs.length;const s=songs[currentSong];audio.src=s.file;if(title)title.textContent=s.title;if(cover)cover.src=s.cover;if(artist)artist.textContent="My Songs";audio.load();updateLike();if(autoplay)audio.play().catch(()=>toastMsg("This local audio file could not be played"));if(playBtn)playBtn.innerHTML=autoplay?'<i class="fa-solid fa-pause"></i>':'<i class="fa-solid fa-play"></i>'}
function playJamendo(track){stopYoutube();source="jamendo";youtubeId=null;jamendoTrack=track;if(youtubeDock)youtubeDock.classList.add("hidden");if(!audio)return;audio.src=track.audio;audio.load();if(title)title.textContent=track.title;if(artist)artist.textContent=`${track.artist} • Jamendo`;if(cover)cover.src=track.cover||"";updateLike();audio.play().then(()=>{if(playBtn)playBtn.innerHTML='<i class="fa-solid fa-pause"></i>'}).catch(()=>toastMsg("This Jamendo track could not be played"))}
function playYoutube(video){stopExternal();source="youtube";youtubeId=video.id;if(audio)audio.pause();if(youtubeDock)youtubeDock.classList.remove("hidden");if(title)title.textContent=video.title;if(artist)artist.textContent=`YouTube • ${video.channel||"Video"}`;if(cover)cover.src=video.cover||`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`;if(duration)duration.textContent="0:00";if(currentTime)currentTime.textContent="0:00";if(progress)progress.value=0;if(youtubeReady&&youtubePlayer)youtubePlayer.loadVideoById(video.id);else toastMsg("YouTube player is loading…")}
function onYouTubeIframeAPIReady(){const el=$("youtubePlayer");if(!el||typeof YT==="undefined")return;youtubePlayer=new YT.Player(el,{height:"124",width:"220",videoId:"",playerVars:{playsinline:1,rel:0},events:{onReady:()=>{youtubeReady=true;if(youtubeId&&source==="youtube")youtubePlayer.loadVideoById(youtubeId)},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){if(playBtn)playBtn.innerHTML='<i class="fa-solid fa-pause"></i>';startYoutubeProgress()}else if(e.data===YT.PlayerState.PAUSED){if(playBtn)playBtn.innerHTML='<i class="fa-solid fa-play"></i>';clearInterval(youtubeTimer)}else if(e.data===YT.PlayerState.ENDED){clearInterval(youtubeTimer);if(repeatOn)youtubePlayer.playVideo();else toastMsg("YouTube track ended")}}}})}
function startYoutubeProgress(){clearInterval(youtubeTimer);youtubeTimer=setInterval(()=>{if(!youtubePlayer||source!=="youtube")return;const d=youtubePlayer.getDuration(),t=youtubePlayer.getCurrentTime();if(currentTime)currentTime.textContent=formatTime(t);if(duration)duration.textContent=formatTime(d);if(progress)progress.value=d?(t/d)*100:0},500)}
function makeCard(s,i){const d=document.createElement("article");d.className="songCard";d.innerHTML=`<img src="${s.cover}" alt="${s.title}"><h3>${s.title}</h3><p>My Songs • Local track</p><button class="cardPlay" data-index="${i}" type="button" aria-label="Play ${s.title}"><i class="fa-solid fa-play"></i></button>`;return d}
function makeYoutubeCard(v){const d=document.createElement("article");d.className="songCard youtubeCard";d.innerHTML=`<img src="${v.cover}" alt=""><h3 title="${v.title}">${v.title}</h3><p>YouTube • ${v.channel||"Video"}</p><button class="cardPlay ytPlay" type="button" aria-label="Play ${v.title}"><i class="fa-solid fa-play"></i></button>`;d.querySelector(".ytPlay").addEventListener("click",e=>{e.stopPropagation();playYoutube(v)});return d}
function makeJamendoCard(v){const d=document.createElement("article");d.className="songCard jamendoCard";d.innerHTML=`<img src="${v.cover||""}" alt=""><h3 title="${v.title}">${v.title}</h3><p>${v.artist} • Jamendo</p><button class="cardPlay jamPlay" type="button" aria-label="Play ${v.title}"><i class="fa-solid fa-play"></i></button>`;d.querySelector(".jamPlay").addEventListener("click",e=>{e.stopPropagation();playJamendo(v)});return d}
function renderCards(target,list=songs){if(!target)return;target.innerHTML="";list.forEach((s,i)=>target.appendChild(makeCard(s,i)));if(!list.length)target.innerHTML='<p class="empty">No songs found.</p>'}
function renderLibrary(){if(!libraryGrid)return;libraryGrid.innerHTML="";songs.forEach((s,i)=>{const d=document.createElement("div");d.className="libraryRow";d.innerHTML=`<img src="${s.cover}" alt=""><div><h3>${s.title}</h3><p>Local track • ${liked.has(i)?"Liked":"In your library"}</p></div>`;d.addEventListener("click",()=>setLocalSong(i,true));libraryGrid.appendChild(d)})}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));const view=$(name+"View");if(!view)return;view.classList.remove("hidden");document.querySelectorAll(".navItem").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="library")renderLibrary();if(name==="search"&&search)search.focus()}
function extractYoutubeId(text){try{const u=new URL(text);if(u.hostname.includes("youtu.be"))return u.pathname.slice(1).split("/")[0];if(u.hostname.includes("youtube.com"))return u.searchParams.get("v")||u.pathname.split("/").pop()}catch(e){}return null}
async function searchJamendo(q){const url=`https://api.jamendo.com/v3.0/tracks/?client_id=${encodeURIComponent(JAMENDO_CLIENT_ID)}&format=json&limit=12&type=single%20albumtrack&audioformat=mp32&search=${encodeURIComponent(q)}`;const r=await fetch(url);const data=await r.json();if(!r.ok||data?.headers?.status!=="success")throw new Error(data?.headers?.error_message||"Jamendo search failed");return(data.results||[]).filter(x=>x.audio).map(x=>({id:x.id,title:x.name,artist:x.artist_name||"Unknown artist",cover:x.image||x.album_image,audio:x.audio,license:x.license_ccurl}))}
async function searchYoutube(q){const key=localStorage.getItem("youtubeApiKey");if(!key)return[];const url=`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&videoCategoryId=10&maxResults=12&q=${encodeURIComponent(q)}&key=${encodeURIComponent(key)}`;const r=await fetch(url);const data=await r.json();if(!r.ok)throw new Error(data.error?.message||"YouTube API error");return(data.items||[]).filter(x=>x.id?.videoId).map(x=>({id:x.id.videoId,title:x.snippet.title.replace(/<[^>]*>/g,""),channel:x.snippet.channelTitle,cover:x.snippet.thumbnails?.high?.url||x.snippet.thumbnails?.medium?.url}))}
async function getTrendingYoutube(){const key=localStorage.getItem("youtubeApiKey");if(!key)return[];const url=`https://www.googleapis.com/youtube/v3/videos?part=snippet&chart=mostPopular&regionCode=IN&videoCategoryId=10&maxResults=12&key=${encodeURIComponent(key)}`;const r=await fetch(url);const data=await r.json();if(!r.ok)throw new Error(data.error?.message||"YouTube trending request failed");return(data.items||[]).map(x=>({id:x.id,title:x.snippet?.title?.replace(/<[^>]*>/g,"")||"Untitled",channel:x.snippet?.channelTitle||"YouTube Music",cover:x.snippet?.thumbnails?.high?.url||x.snippet?.thumbnails?.medium?.url||`https://i.ytimg.com/vi/${x.id}/hqdefault.jpg`}))}
async function loadTrending(){if(!songCards)return;songCards.innerHTML='<p class="empty">Loading India’s trending music…</p>';const key=localStorage.getItem("youtubeApiKey");if(!key){renderCards(songCards);return}try{const trending=await getTrendingYoutube();songCards.innerHTML="";if(!trending.length){renderCards(songCards);return}trending.forEach(v=>songCards.appendChild(makeYoutubeCard(v)))}catch(e){renderCards(songCards);toastMsg("India trending unavailable — showing your local songs")}}
async function searchAll(q){showView("search");if(!searchCards)return;searchCards.innerHTML='<p class="empty">Searching Jamendo and YouTube…</p>';try{const results=await Promise.allSettled([searchJamendo(q),searchYoutube(q)]);const jam=results[0].status==="fulfilled"?results[0].value:[];const yt=results[1].status==="fulfilled"?results[1].value:[];searchCards.innerHTML="";if(!jam.length&&!yt.length){searchCards.innerHTML='<p class="empty">No results. Try another search.</p>';return}jam.forEach(v=>searchCards.appendChild(makeJamendoCard(v)));yt.forEach(v=>searchCards.appendChild(makeYoutubeCard(v)));if(results[0].status==="rejected")toastMsg("Jamendo search unavailable");if(results[1].status==="rejected"&&localStorage.getItem("youtubeApiKey"))toastMsg("YouTube search failed — Jamendo results are still available")}catch(e){searchCards.innerHTML=`<p class="empty">${e.message}</p>`;toastMsg(e.message)}}

function init(){
 setLocalSong(currentSong);
 renderCards(songCards);
 renderCards(searchCards);
 loadTrending();

 if(playBtn)playBtn.addEventListener("click",()=>{if(source==="youtube"){if(!youtubePlayer||!youtubeReady){toastMsg("YouTube player is still loading");return}const state=youtubePlayer.getPlayerState();if(state===YT.PlayerState.PLAYING)youtubePlayer.pauseVideo();else youtubePlayer.playVideo();return}if(audio?.paused){audio.play().then(()=>{if(playBtn)playBtn.innerHTML='<i class="fa-solid fa-pause"></i>'}).catch(()=>toastMsg("This audio file could not be played"))}else{audio.pause();playBtn.innerHTML='<i class="fa-solid fa-play"></i>'}});
 if(nextBtn)nextBtn.addEventListener("click",()=>{if(source!=="local"){toastMsg("Choose another search result to change tracks");return}let n;if(shuffleOn&&songs.length>1){do n=Math.floor(Math.random()*songs.length);while(n===currentSong)}else n=currentSong+1;setLocalSong(n,true)});
 if(prevBtn)prevBtn.addEventListener("click",()=>{if(source!=="local"){toastMsg("Previous is available for your local queue");return}if(audio.currentTime>3){audio.currentTime=0;return}setLocalSong(currentSong-1,true)});
 if(shuffleBtn)shuffleBtn.addEventListener("click",()=>{shuffleOn=!shuffleOn;shuffleBtn.classList.toggle("active",shuffleOn);toastMsg(shuffleOn?"Shuffle on":"Shuffle off")});
 if(repeatBtn)repeatBtn.addEventListener("click",()=>{repeatOn=!repeatOn;repeatBtn.classList.toggle("active",repeatOn);toastMsg(repeatOn?"Repeat on":"Repeat off")});
 if(likeBtn)likeBtn.addEventListener("click",()=>{if(source!=="local"){toastMsg(source==="jamendo"?"Jamendo favorites require Jamendo login":"YouTube likes are managed by YouTube");return}liked.has(currentSong)?liked.delete(currentSong):liked.add(currentSong);updateLike();renderLibrary();toastMsg(liked.has(currentSong)?"Added to Liked Songs":"Removed from Liked Songs")});
 if(progress)progress.addEventListener("input",()=>{const p=Number(progress.value)/100;if(source==="youtube"&&youtubePlayer&&youtubeReady)youtubePlayer.seekTo(p*youtubePlayer.getDuration(),true);else if(audio?.duration)audio.currentTime=p*audio.duration});
 if(volume)volume.addEventListener("input",()=>{audio.volume=volume.value;if(youtubePlayer&&youtubeReady)youtubePlayer.setVolume(Number(volume.value)*100)});
 if(audio){audio.addEventListener("loadedmetadata",()=>{if(source!=="youtube"&&duration)duration.textContent=formatTime(audio.duration)});audio.addEventListener("timeupdate",()=>{if(source==="local"||source==="jamendo"){if(currentTime)currentTime.textContent=formatTime(audio.currentTime);if(progress)progress.value=audio.duration?(audio.currentTime/audio.duration)*100:0}});audio.addEventListener("play",()=>{if(source!=="youtube"&&playBtn)playBtn.innerHTML='<i class="fa-solid fa-pause"></i>'});audio.addEventListener("pause",()=>{if(source!=="youtube"&&playBtn)playBtn.innerHTML='<i class="fa-solid fa-play"></i>'});audio.addEventListener("ended",()=>{if(source==="jamendo"){if(repeatOn){audio.currentTime=0;audio.play()}else if(playBtn)playBtn.innerHTML='<i class="fa-solid fa-play"></i>'}else if(source==="local"){if(repeatOn){audio.currentTime=0;audio.play()}else nextBtn?.click()}})}
 document.addEventListener("click",e=>{const card=e.target.closest(".cardPlay");if(card&&card.dataset.index!==undefined){e.stopPropagation();setLocalSong(Number(card.dataset.index),true)}});
 document.querySelectorAll(".navItem").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
 $("showAll")?.addEventListener("click",()=>showView("library"));
 $("refreshTrending")?.addEventListener("click",loadTrending);
 $("back")?.addEventListener("click",()=>window.history.back());
 $("forward")?.addEventListener("click",()=>window.history.forward());
 $("addPlaylist")?.addEventListener("click",()=>toastMsg("Playlist creation coming soon"));
 $("queue")?.addEventListener("click",()=>toastMsg(`${songs.length} local songs in queue`));
 $("ytKey")?.addEventListener("click",()=>{const old=localStorage.getItem("youtubeApiKey")||"";const key=prompt("Paste your YouTube Data API v3 key. Do not paste an OAuth secret here.",old);if(key!==null){if(key.trim())localStorage.setItem("youtubeApiKey",key.trim());else localStorage.removeItem("youtubeApiKey");toastMsg(key?.trim()?"YouTube key saved — loading trending music":"YouTube key removed");if(key?.trim())loadTrending()}});
 if(search)search.addEventListener("keydown",e=>{if(e.key!=="Enter")return;const q=search.value.trim();if(!q)return;const id=extractYoutubeId(q);if(id){playYoutube({id,title:"YouTube video",channel:"YouTube",cover:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`});return}searchAll(q)});
}

if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();