const songs=[
 {title:"Song 1",file:"songs/song1.mp3",cover:"images/cover1.jpg"},
 {title:"Song 2",file:"songs/song2.mp3",cover:"images/cover2.jpg"}
];
let currentSong=0,shuffleOn=false,repeatOn=false,liked=new Set(),source="local",youtubeId=null,youtubePlayer=null,youtubeReady=false,youtubeTimer=null;
const audio=document.getElementById("audio"),title=document.getElementById("title"),cover=document.getElementById("cover"),playBtn=document.getElementById("play"),prevBtn=document.getElementById("prev"),nextBtn=document.getElementById("next"),progress=document.getElementById("progress"),currentTime=document.getElementById("currentTime"),duration=document.getElementById("duration"),volume=document.getElementById("volume"),artist=document.getElementById("artist"),likeBtn=document.getElementById("like"),toast=document.getElementById("toast"),search=document.getElementById("search"),youtubeDock=document.getElementById("youtubeDock");
const songCards=document.getElementById("songCards"),searchCards=document.getElementById("searchCards"),libraryGrid=document.getElementById("libraryGrid");
function formatTime(t){if(!Number.isFinite(t))return"0:00";const m=Math.floor(t/60),s=Math.floor(t%60).toString().padStart(2,"0");return`${m}:${s}`}
function toastMsg(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove("show"),2600)}
function updateLike(){likeBtn.innerHTML=liked.has(currentSong)?'<i class="fa-solid fa-heart"></i>':'<i class="fa-regular fa-heart"></i>';likeBtn.classList.toggle("liked",liked.has(currentSong))}
function stopYoutube(){if(youtubePlayer&&youtubeReady){try{youtubePlayer.stopVideo()}catch(e){}}clearInterval(youtubeTimer);youtubeTimer=null}
function setLocalSong(i,autoplay=false){stopYoutube();source="local";youtubeId=null;youtubeDock.classList.add("hidden");currentSong=(i+songs.length)%songs.length;const s=songs[currentSong];audio.src=s.file;title.textContent=s.title;cover.src=s.cover;artist.textContent="My Songs";audio.load();updateLike();if(autoplay)audio.play().catch(()=>toastMsg("This local audio file could not be played"));playBtn.innerHTML=autoplay?'<i class="fa-solid fa-pause"></i>':'<i class="fa-solid fa-play"></i>'}
function playYoutube(video){stopYoutube();source="youtube";youtubeId=video.id;audio.pause();youtubeDock.classList.remove("hidden");title.textContent=video.title;artist.textContent=`YouTube • ${video.channel||"Video"}`;cover.src=video.cover||`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`;duration.textContent="0:00";currentTime.textContent="0:00";progress.value=0;if(youtubeReady&&youtubePlayer)youtubePlayer.loadVideoById(video.id);else toastMsg("YouTube player is loading…");}
function onYouTubeIframeAPIReady(){youtubePlayer=new YT.Player("youtubePlayer",{height:"124",width:"220",videoId:"",playerVars:{playsinline:1,rel:0},events:{onReady:()=>{youtubeReady=true;if(youtubeId&&source==="youtube")youtubePlayer.loadVideoById(youtubeId)},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){playBtn.innerHTML='<i class="fa-solid fa-pause"></i>';startYoutubeProgress()}else if(e.data===YT.PlayerState.PAUSED){playBtn.innerHTML='<i class="fa-solid fa-play"></i>';clearInterval(youtubeTimer)}else if(e.data===YT.PlayerState.ENDED){clearInterval(youtubeTimer);if(repeatOn)youtubePlayer.playVideo();else nextBtn.click()}}}})}
function startYoutubeProgress(){clearInterval(youtubeTimer);youtubeTimer=setInterval(()=>{if(!youtubePlayer||source!=="youtube")return;const d=youtubePlayer.getDuration(),t=youtubePlayer.getCurrentTime();currentTime.textContent=formatTime(t);duration.textContent=formatTime(d);progress.value=d?(t/d)*100:0},500)}
function makeCard(s,i){const d=document.createElement("article");d.className="songCard";d.innerHTML=`<img src="${s.cover}" alt="${s.title}"><h3>${s.title}</h3><p>My Songs • Local track</p><button class="cardPlay" data-index="${i}" aria-label="Play ${s.title}"><i class="fa-solid fa-play"></i></button>`;return d}
function makeYoutubeCard(v){const d=document.createElement("article");d.className="songCard youtubeCard";d.innerHTML=`<img src="${v.cover}" alt=""><h3>${v.title}</h3><p>YouTube • ${v.channel||"Video"}</p><button class="cardPlay ytPlay" aria-label="Play ${v.title}"><i class="fa-solid fa-play"></i></button>`;d.querySelector(".ytPlay").onclick=()=>playYoutube(v);return d}
function renderCards(target,list=songs){target.innerHTML="";list.forEach((s,i)=>target.appendChild(makeCard(s,i)));if(!list.length)target.innerHTML='<p class="empty">No songs found.</p>'}
function renderLibrary(){libraryGrid.innerHTML="";songs.forEach((s,i)=>{const d=document.createElement("div");d.className="libraryRow";d.innerHTML=`<img src="${s.cover}" alt=""><div><h3>${s.title}</h3><p>Local track • ${liked.has(i)?"Liked":"In your library"}</p></div>`;d.onclick=()=>setLocalSong(i,true);libraryGrid.appendChild(d)})}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.getElementById(name+"View").classList.remove("hidden");document.querySelectorAll(".navItem").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="library")renderLibrary();if(name==="search")search.focus()}
function extractYoutubeId(text){try{const u=new URL(text);if(u.hostname.includes("youtu.be"))return u.pathname.slice(1).split("/")[0];if(u.hostname.includes("youtube.com"))return u.searchParams.get("v")||u.pathname.split("/").pop()}catch(e){}return null}
async function searchYoutube(q){const key=localStorage.getItem("youtubeApiKey");if(!key){showView("search");searchCards.innerHTML='<p class="empty">No API key needed for direct links. Paste a YouTube URL above and press Enter. For song search, click Connect and add a YouTube Data API v3 key.</p>';toastMsg("Paste a YouTube URL, or connect a YouTube API key for search");return}showView("search");searchCards.innerHTML='<p class="empty">Searching YouTube…</p>';try{const url=`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&videoCategoryId=10&maxResults=12&q=${encodeURIComponent(q)}&key=${encodeURIComponent(key)}`;const r=await fetch(url);const data=await r.json();if(!r.ok){const reason=data?.error?.errors?.[0]?.reason||"unknown";if(reason==="keyInvalid"){localStorage.removeItem("youtubeApiKey");throw new Error("API key is invalid. Create a new key and make sure YouTube Data API v3 is enabled.")}if(reason==="quotaExceeded"){throw new Error("YouTube search quota is exhausted. Try again later or use a direct YouTube URL.")}if(r.status===403){throw new Error("YouTube rejected this key. Check API restrictions and that YouTube Data API v3 is enabled.")}throw new Error(data.error?.message||"YouTube API error")}const results=(data.items||[]).filter(x=>x.id?.videoId).map(x=>({id:x.id.videoId,title:x.snippet.title.replace(/<[^>]*>/g,""),channel:x.snippet.channelTitle,cover:x.snippet.thumbnails?.high?.url||x.snippet.thumbnails?.medium?.url}));searchCards.innerHTML="";results.forEach(v=>searchCards.appendChild(makeYoutubeCard(v)));if(!results.length)searchCards.innerHTML='<p class="empty">No YouTube music results.</p>'}catch(e){searchCards.innerHTML=`<p class="empty">${e.message}</p>`;toastMsg(e.message)}}
setLocalSong(currentSong);renderCards(songCards);renderCards(searchCards);
playBtn.onclick=()=>{if(source==="youtube"){if(!youtubePlayer||!youtubeReady){toastMsg("YouTube player is still loading");return}const state=youtubePlayer.getPlayerState();if(state===YT.PlayerState.PLAYING)youtubePlayer.pauseVideo();else youtubePlayer.playVideo();return}if(audio.paused){audio.play().then(()=>playBtn.innerHTML='<i class="fa-solid fa-pause"></i>').catch(()=>toastMsg("This audio file could not be played"))}else{audio.pause();playBtn.innerHTML='<i class="fa-solid fa-play"></i>'}};
nextBtn.onclick=()=>{if(source==="youtube"){toastMsg("Choose another YouTube result to change tracks");return}let n;if(shuffleOn&&songs.length>1){do n=Math.floor(Math.random()*songs.length);while(n===currentSong)}else n=currentSong+1;setLocalSong(n,true)};
prevBtn.onclick=()=>{if(source==="youtube"){toastMsg("Previous is available for your local queue");return}if(audio.currentTime>3){audio.currentTime=0;return}setLocalSong(currentSong-1,true)};
shuffle.onclick=()=>{shuffleOn=!shuffleOn;shuffle.classList.toggle("active",shuffleOn);toastMsg(shuffleOn?"Shuffle on":"Shuffle off")};repeat.onclick=()=>{repeatOn=!repeatOn;repeat.classList.toggle("active",repeatOn);toastMsg(repeatOn?"Repeat on":"Repeat off")};
likeBtn.onclick=()=>{if(source!=="local"){toastMsg("YouTube likes are managed by YouTube");return}liked.has(currentSong)?liked.delete(currentSong):liked.add(currentSong);updateLike();renderLibrary();toastMsg(liked.has(currentSong)?"Added to Liked Songs":"Removed from Liked Songs")};
progress.oninput=()=>{const p=Number(progress.value)/100;if(source==="youtube"&&youtubePlayer&&youtubeReady){youtubePlayer.seekTo(p*youtubePlayer.getDuration(),true)}else if(audio.duration)audio.currentTime=p*audio.duration};volume.oninput=()=>{audio.volume=volume.value;if(youtubePlayer&&youtubeReady)youtubePlayer.setVolume(Number(volume.value)*100)};
audio.addEventListener("loadedmetadata",()=>{if(source==="local")duration.textContent=formatTime(audio.duration)});audio.addEventListener("timeupdate",()=>{if(source!=="local")return;currentTime.textContent=formatTime(audio.currentTime);progress.value=audio.duration?(audio.currentTime/audio.duration)*100:0});audio.addEventListener("play",()=>{if(source==="local")playBtn.innerHTML='<i class="fa-solid fa-pause"></i>'});audio.addEventListener("pause",()=>{if(source==="local")playBtn.innerHTML='<i class="fa-solid fa-play"></i>'});audio.addEventListener("ended",()=>{if(source!=="local")return;if(repeatOn){audio.currentTime=0;audio.play()}else nextBtn.click()});
document.addEventListener("click",e=>{const card=e.target.closest(".cardPlay");if(card&&card.dataset.index!==undefined){e.stopPropagation();setLocalSong(Number(card.dataset.index),true)}});
document.querySelectorAll(".navItem").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.getElementById("showAll").onclick=()=>showView("library");document.getElementById("back").onclick=()=>window.history.back();document.getElementById("forward").onclick=()=>window.history.forward();document.getElementById("addPlaylist").onclick=()=>toastMsg("Playlist creation coming soon");document.getElementById("queue").onclick=()=>toastMsg(`${songs.length} local songs in queue`);
document.getElementById("ytKey").onclick=()=>{const old=localStorage.getItem("youtubeApiKey")||"";const key=prompt("Paste your YouTube Data API v3 key. Do not paste an OAuth secret here.",old);if(key!==null){if(key.trim())localStorage.setItem("youtubeApiKey",key.trim());else localStorage.removeItem("youtubeApiKey");toastMsg(key?.trim()?"YouTube key saved — try a search":"YouTube key removed")}};
search.onkeydown=e=>{if(e.key!=="Enter")return;const q=search.value.trim();if(!q)return;const id=extractYoutubeId(q);if(id){playYoutube({id,title:"YouTube video",channel:"YouTube",cover:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`});return}searchYoutube(q)};
